---
name: Acme-Gosub
version: 0.1.3
author:
  - |-
    Shlomi Fish ( C<< <shlomif@iglu.org.il> >> ) converted Switch.pm to become 
    Acme::Gosub.
abstract: Implement BASIC-like "gosub" and "greturn" in Perl
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Filter::Util::Call: 0
  Text::Balanced: 0
build_requires:
  Test::More: 0
provides:
  Acme::Gosub:
    file: lib/Acme/Gosub.pm
    version: 0.1.3
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
