---
name: Acme-Gosub
version: 0.1.4
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
abstract: Implement BASIC-like "gosub" and "greturn" in Perl
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: https://svn.berlios.de/svnroot/repos/web-cpan/Acme-Gosub/
requires:
  Filter::Util::Call: 0
  Text::Balanced: 0
build_requires:
  Test::More: 0
provides:
  Acme::Gosub:
    file: lib/Acme/Gosub.pm
    version: 0.1.4
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
keywords:
  - Acme
  - BASIC
  - black magick
  - gosub
  - joke
  - retro
  - source filter
  - subroutine
